version: 2

models:
  - name: trajets_summary
    description: "Résumé des trajets avec le nombre de trajets et le montant total par segment de client et type de véhicule."
    columns:
      - name: nom_segment
        description: "Le segment auquel appartient le client (ex : Particulier, VIP, Entreprise)."
        tests:
          - not_null
      - name: nom_type_vehicule
        description: "Le type de véhicule utilisé pour le trajet (ex : Berline, SUV)."
        tests:
          - not_null
      - name: nombre_trajets
        description: "Le nombre total de trajets effectués pour ce type de véhicule et ce segment de client."
      - name: total_revenus
        description: "Le montant total des revenus générés par les trajets pour ce type de véhicule et ce segment de client."

version: 2

models:
  - name: revenus_par_segment_et_type
    description: "Modèle qui calcule le nombre total de trajets et le montant total des revenus par segment de client et type de véhicule."
    columns:
      - name: nom_segment
        description: "Le segment de client (Entreprise, VIP, Particulier)."
      - name: nom_type_vehicule
        description: "Le type de véhicule (SUV, Berline)."
      - name: nombre_trajets
        description: "Le nombre de trajets réalisés pour ce type de véhicule et ce segment."
      - name: total_revenus
        description: "Le montant total des revenus générés par ce type de véhicule et ce segment."
